name: BitWallet iOS build and test

on:
  push:
    branches:
      - "**" # Runs on all branches!
  pull_request:
    branches-ignore:
      - master
      - deployment-next # Ignore PRs merging into these branches!
jobs:
  build:
    if: |
      contains(github.event.head_commit.message, 'ios-dev') || 
      contains(github.event.head_commit.message, 'ios-qa') ||
      contains(github.event.head_commit.message, 'ios-prod')
    name: Build iOS - ${{ github.event.head_commit.message }}
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Load Environment Variables
        id: load_env
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"ios-dev"* ]]; then
            ENV_FILE=".env.dev"
          elif [[ "${{ github.event.head_commit.message }}" == *"ios-qa"* ]]; then
            ENV_FILE=".env.qa"
          elif [[ "${{ github.event.head_commit.message }}" == *"ios-prod"* ]]; then
            ENV_FILE=".env.prod"
          else
            echo "No matching env file for commit message"
            exit 1
          fi
          echo "Using $ENV_FILE"
          export $(grep -v '^#' $ENV_FILE | xargs)
          echo "BASE_URL=$BASE_URL" >> $GITHUB_ENV
          echo "API_TOKEN=$API_TOKEN" >> $GITHUB_ENV
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      - name: Build
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
          BASE_URL: ${{ env.BASE_URL }}
          API_TOKEN: ${{ env.API_TOKEN }}
        run: |
          # xcrun xctrace returns via stderr, not the expected stdout (see https://developer.apple.com/forums/thread/663959)
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
          if [ $scheme = default ]; then scheme=$(cat default); fi
          if [ "`ls -A | grep -i \\.xcworkspace$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj$`"; fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          xcodebuild build-for-testing -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,name=$device"
      - name: Test
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
          BASE_URL: ${{ env.BASE_URL }}
          API_TOKEN: ${{ env.API_TOKEN }}
        run: |
          # xcrun xctrace returns via stderr, not the expected stdout (see https://developer.apple.com/forums/thread/663959)
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
          if [ $scheme = default ]; then scheme=$(cat default); fi
          if [ "`ls -A | grep -i \\.xcworkspace$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj$`"; fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          xcodebuild test-without-building -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,name=$device"
